swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: Sample API

basePath: /v1

# Replace this with the path to your actual implementation
host: localhost:8080

# Describe your paths here
paths:
  "/pet/{petId}":
    get:
      tags:
        - pet
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      x-swagger-router-controller: io.swagger.sample.controllers.SampleController
      consumes:
        - application/xml
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          type: integer
          format: int32
          # enum:
          #   - 0
          #   - 1
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Pet"
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found  
definitions:
  Pet:
    type: object
    properties:
      id:
        type: integer
      user:
        type: string
      name:
        type: string
      age:
        type: integer
      size:
        type: string
      petReqEnum:
        type: string 
      hostFeatureEnum:
        type: string
      petBreed:
        type: string  